import React from 'react';

/**
 * Zanpath AI - Terms of Service Component
 * Optimized for Paddle Compliance (2026)
 */
export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#eaf4f2] text-gray-800 px-6 py-16 font-sans">
      <div className="max-w-3xl mx-auto p-8">
        <h1 className="text-3xl font-bold mb-8 border-b pb-4">Terms of Service</h1>

        <div className="space-y-6 leading-relaxed">
          {/* Section 1: Business Identity - CRITICAL FOR PADDLE */}
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Agreement to Terms</h2>
            <p>
              These Terms of Service govern your use of <strong>Zanpath AI</strong> (the "Service"), 
              which is owned and operated by <strong>Zanpath AI</strong> ("we," "us," or "our"). 
              By accessing or using our website located at <strong>zanpath.com</strong>, 
              you agree to be bound by these terms. If you do not agree, please do not use the Service.
            </p>
          </section>

          {/* Section 2: Product Description */}
          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p>
              <strong>Zanpath AI</strong> provides AI-generated digital content designed for personal 
              reflection and cultural exploration. Our products consist of downloadable PDF 
              reports generated based on user input.
            </p>
          </section>

          {/* Section 3: Disclaimer - Important for Compliance */}
          <section>
            <h2 className="text-xl font-semibold mb-3">3. Entertainment Purposes Only</h2>
            <p>
              The content provided by Zanpath AI is for <strong>entertainment and self-exploration 
              purposes only</strong>. It does not constitute professional, medical, legal, or 
              financial advice. We make no guarantees regarding the accuracy, outcomes, or 
              interpretations of the AI-generated content.
            </p>
          </section>

          {/* Section 4: Payments and Merchant of Record */}
          <section>
            <h2 className="text-xl font-semibold mb-3">4. Payments</h2>
            <p>
              Our order process is conducted by our online reseller <strong>Paddle.com</strong>. 
              Paddle is the Merchant of Record for all our orders. Paddle provides all customer 
              service inquiries and handles returns.
            </p>
          </section>

          {/* Section 5: Intellectual Property */}
          <section>
            <h2 className="text-xl font-semibold mb-3">5. Intellectual Property</h2>
            <p>
              All content, logos, and digital reports generated by Zanpath AI are the intellectual 
              property of Zanpath AI. You are granted a personal, non-exclusive license to use 
              the reports for private, non-commercial purposes.
            </p>
          </section>

          {/* Section 6: Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold mb-3">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Zanpath AI shall not be liable for any 
              indirect, incidental, or consequential damages arising out of your use of the Service.
            </p>
          </section>

          {/* Section 7: Contact Info */}
          <section className="pt-6 border-t">
            <p className="text-sm text-gray-600">
              If you have any questions about these Terms, please contact us at: 
              <br />
              <strong>Email: alaricegaye@gmail.com</strong>
            </p>
            <p className="text-sm text-gray-500 mt-2">
              Last Updated: January 20, 2026
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}