import { Document, Page, Text, View, StyleSheet, Font, Image } from '@react-pdf/renderer';
import path from 'path';

// 1. 注册中文字体 (确保文件名与 public/fonts/ 下的文件完全一致)
const fontBold = path.join(process.cwd(), 'public/fonts/NotoSansSC-Bold.ttf');
const fontRegular = path.join(process.cwd(), 'public/fonts/NotoSansSC-Regular.ttf');
// Logo 图片路径
const logoPath = path.join(process.cwd(), 'public/logo.png');

Font.register({
  family: 'NotoSansSC',
  fonts: [
    { src: fontRegular, fontWeight: 'normal' },
    { src: fontBold, fontWeight: 'bold' },
  ],
});

const styles = StyleSheet.create({
  page: {
    paddingTop: 50,
    paddingBottom: 70,
    paddingLeft: 60,
    paddingRight: 60,
    fontFamily: 'NotoSansSC',
    backgroundColor: '#ffffff',
  },
  header: {
    flexDirection: 'row', // 开启横向排列
    justifyContent: 'space-between', // Logo 与标题两端对齐
    alignItems: 'flex-start',
    marginBottom: 25,
    borderBottomWidth: 1,
    borderBottomColor: '#d1d1d1',
    paddingBottom: 15,
  },
  logo: {
    width: 60, // 调整 Logo 大小
    height: 60,
  },
  headerTextContent: {
    flex: 1,
    marginLeft: 15, // 文字与 Logo 的间距
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1a365d', // 颜色优化：深蓝色更显专业与定制感
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 9,
    color: '#888',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  content: {
    marginTop: 15,
    fontSize: 11,
    lineHeight: 1.8,
    color: '#333333',
    textAlign: 'left', 
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 60,
    right: 60,
    borderTopWidth: 0.5,
    borderTopColor: '#eeeeee',
    paddingTop: 15,
    textAlign: 'center',
    fontSize: 8.5,
    color: '#aaaaaa',
  },
  footerBrand: {
    marginTop: 5,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#999',
  }
});

export const AnalysisReportPDF = ({ data, lang = 'en' }: any) => {
  return (
    <Document title={data.title || "ZanPath AI Report"}>
      <Page size="A4" style={styles.page}>
        {/* 页眉部分：Logo + 标题 */}
        <View style={styles.header}>
          {/* 左侧放置 Logo */}
          <Image src={logoPath} style={styles.logo} />
          
          {/* 右侧放置文字信息 */}
          <View style={styles.headerTextContent}>
            <Text style={styles.title}>{data.title}</Text>
            <Text style={styles.subtitle}>ZanPath AI - Spiritual Guidance Report</Text>
          </View>
        </View>

        {/* 正文内容 */}
        <View>
          <Text style={styles.content}>
            {data.content}
          </Text>
        </View>

        {/* 页脚部分 */}
        <View style={styles.footer}>
          <Text>
            {lang === 'es' 
              ? 'Este informe fue generado por IA y es solo para fines espirituales y de orientación.' 
              : 'This report was generated by AI and is for spiritual and guidance purposes only.'}
          </Text>
          <Text style={styles.footerBrand}>© 2026 ZanPath AI</Text>
        </View>
      </Page>
    </Document>
  );
};