// config/daily-reflections.ts

export const REFLECTION_UI = {
  en: {
    title: "Daily Reflection",
    button: "Draw Today's Card",
    footer: "Come back tomorrow for a new perspective.",
  },
  es: {
    title: "Reflexión Diaria",
    button: "Sacar Carta de Hoy",
    footer: "Vuelve mañana para una nueva perspectiva.",
  }
};

export const DAILY_REFLECTIONS = [
 { en: "Clarity deepens with patience.", es: "La claridad se profundiza con la paciencia." },
  { en: "Your attention stabilizes momentum.", es: "Tu atención estabiliza el impulso." },
  { en: "Reflection refines direction.", es: "La reflexión refina la dirección." },
  { en: "Gentle awareness keeps things aligned.", es: "La conciencia gentil mantiene las cosas alineadas." },
  { en: "You can hold focus without strain.", es: "Puedes mantener el enfoque sin esfuerzo." },
  { en: "Small refinements support continuity.", es: "Pequeños refinamientos apoyan la continuidad." },
  { en: "Calm effort protects balance.", es: "El esfuerzo tranquilo protege el equilibrio." },
  { en: "Awareness reduces resistance.", es: "La conciencia reduce la resistencia." },
  { en: "Your presence shapes today’s flow.", es: "Tu presencia moldea el flujo de hoy." },
  { en: "Steady attention supports reliability.", es: "La atención constante apoya la confiabilidad." },
  { en: "You may move forward quietly.", es: "Puedes avanzar en silencio." },
  { en: "Observation reveals subtle opportunities.", es: "La observación revela oportunidades sutiles." },
  { en: "Patience allows clarity to emerge.", es: "La paciencia permite que la claridad emerja." },
  { en: "Your energy responds to calm focus.", es: "Tu energía responde al enfoque tranquilo." },
  { en: "Alignment feels natural today.", es: "La alineación se siente natural hoy." },
  { en: "Perspective shifts with quiet observation.", es: "La perspectiva cambia con la observación silenciosa." },
  { en: "Every step is part of the path.", es: "Cada paso es parte del camino." },
  { en: "Stability grows from mindful pacing.", es: "La estabilidad surge de un ritmo consciente." },
  { en: "Focus brings subtle details into view.", es: "El enfoque hace que los detalles sutiles sean visibles." },
  { en: "Consistency protects your momentum.", es: "La consistencia protege tu impulso." },
  { en: "Small actions create steady progress.", es: "Las pequeñas acciones crean un progreso constante." },
  { en: "Your presence is enough for today.", es: "Tu presencia es suficiente por hoy." },
  { en: "Patience reveals what speed hides.", es: "La paciencia revela lo que la velocidad oculta." },
  { en: "Gentle shifts lead to new paths.", es: "Los cambios sutiles conducen a nuevos caminos." },
  { en: "Balance is maintained by small adjustments.", es: "El equilibrio se mantiene mediante pequeños ajustes." },
  { en: "Focus allows potential to unfold.", es: "El enfoque permite que el potencial se despliegue." },
  { en: "Calm attention clears the way.", es: "La atención tranquila despeja el camino." },
  { en: "Awareness brings ease to action.", es: "La conciencia aporta facilidad a la acción." },
  { en: "Trust the rhythm of your attention.", es: "Confía en el ritmo de tu atención." },
  { en: "Steady focus builds lasting strength.", es: "El enfoque constante construye una fuerza duradera." },
  { en: "Observe without the need to change.", es: "Observa sin la necesidad de cambiar." },
  { en: "Small steps build great journeys.", es: "Pequeños pasos construyen grandes viajes." },
  { en: "Quiet effort yields strong results.", es: "El esfuerzo silencioso da resultados sólidos." },
  { en: "Clarity comes in the quiet moments.", es: "La claridad llega en los momentos de quietud." },
  { en: "Your path unfolds one breath at a time.", es: "Tu camino se despliega un respiro a la vez." },
  { en: "Flow is found in gentle focus.", es: "El flujo se encuentra en el enfoque gentil." },
  { en: "Stability is a quiet practice.", es: "La estabilidad es una práctica silenciosa." },
  { en: "Attention is the seed of growth.", es: "La atención es la semilla del crecimiento." },
  { en: "Patience stabilizes your energy.", es: "La paciencia estabiliza tu energía." },
  { en: "Every moment is a new beginning.", es: "Cada momento es un nuevo comienzo." },
  { en: "Gentle focus dissolves obstacles.", es: "El enfoque gentil disuelve los obstáculos." },
  { en: "Awareness is the light on your path.", es: "La conciencia es la luz en tu camino." },
  { en: "Your energy follows your intent.", es: "Tu energía sigue a tu intención." },
  { en: "Steady steps lead to far horizons.", es: "Los pasos constantes llevan a horizontes lejanos." },
  { en: "Calmness is a form of power.", es: "La calma es una forma de poder." },
  { en: "Small choices shape your reality.", es: "Las pequeñas elecciones moldean tu realidad." },
  { en: "Observe the flow with an open heart.", es: "Observa el flujo con un corazón abierto." },
  { en: "Patience is a quiet strength.", es: "La paciencia es una fuerza silenciosa." },
  { en: "Focus brings clarity to the chaos.", es: "El enfoque aporta claridad al caos." },
  { en: "Every breath is an act of presence.", es: "Cada respiro es un acto de presencia." },
  { en: "Gentle persistence achieves much.", es: "La persistencia gentil logra mucho." },
  { en: "Stability is found within.", es: "La estabilidad se encuentra en el interior." },
  { en: "Awareness simplifies the complex.", es: "La conciencia simplifica lo complejo." },
  { en: "Trust your inner timing.", es: "Confía en tus tiempos internos." },
  { en: "Steady focus reveals the truth.", es: "El enfoque constante revela la verdad." },
  { en: "Small actions build momentum.", es: "Las pequeñas acciones generan impulso." },
  { en: "Calm effort reaches the goal.", es: "El esfuerzo tranquilo alcanza la meta." },
  { en: "Observe with curiosity, not judgment.", es: "Observa con curiosidad, no con juicio." },
  { en: "Patience allows things to mature.", es: "La paciencia permite que las cosas maduren." },
  { en: "Focus on the step you are taking.", es: "Enfócate en el paso que estás dando." },
  { en: "Awareness brings peace to the mind.", es: "La conciencia trae paz a la mente." },
  { en: "Your path is clear in the light of focus.", es: "Tu camino es claro a la luz del enfoque." },
  { en: "Gentle steps create a firm foundation.", es: "Los pasos gentiles crean una base firme." },
  { en: "Stability grows with every calm breath.", es: "La estabilidad crece con cada respiro tranquilo." },
  { en: "Focus is the key to alignment.", es: "El enfoque es la clave para la alineación." },
  { en: "Observe the subtle changes within.", es: "Observa los cambios sutiles en tu interior." },
  { en: "Patience dissolves the sense of hurry.", es: "La paciencia disuelve el sentido de urgencia." },
  { en: "Every action is a seed of potential.", es: "Cada acción es una semilla de potencial." },
  { en: "Gentle attention brings deep insight.", es: "La atención gentil aporta una visión profunda." },
  { en: "Awareness keeps you centered.", es: "La conciencia te mantiene centrado." },
  { en: "Trust the process of unfolding.", es: "Confía en el proceso de desarrollo." },
  { en: "Steady focus builds inner quiet.", es: "El enfoque constante construye quietud interior." },
  { en: "Small refinements lead to perfection.", es: "Los pequeños refinamientos llevan a la perfección." },
  { en: "Calmness allows wisdom to speak.", es: "La calma permite que la sabiduría hable." },
  { en: "Observe the world with fresh eyes.", es: "Observa el mundo con ojos frescos." },
  { en: "Patience is the art of trusting.", es: "La paciencia es el arte de confiar." },
  { en: "Focus on the present moment.", es: "Enfócate en el momento presente." },
  { en: "Awareness brings clarity to action.", es: "La conciencia aporta claridad a la acción." },
  { en: "Your path is unique to you.", es: "Tu camino es único para ti." },
  { en: "Gentle persistence opens doors.", es: "La persistencia gentil abre puertas." },
  { en: "Stability is maintained through focus.", es: "La estabilidad se mantiene mediante el enfoque." },
  { en: "Observe the beauty in the small things.", es: "Observa la belleza en las cosas pequeñas." },
  { en: "Patience allows for natural growth.", es: "La paciencia permite el crecimiento natural." },
  { en: "Every breath brings you back home.", es: "Cada respiro te trae de vuelta a casa." },
  { en: "Gentle focus aligns your energy.", es: "El enfoque gentil alinea tu energía." },
  { en: "Awareness is the foundation of peace.", es: "La conciencia es la base de la paz." },
  { en: "Trust your inner wisdom today.", es: "Confía en tu sabiduría interior hoy." },
  { en: "Steady focus overcomes obstacles.", es: "El enfoque constante supera los obstáculos." },
  { en: "Small steps lead to great heights.", es: "Los pasos pequeños llevan a grandes alturas." },
  { en: "Calm effort is more effective.", es: "El esfuerzo tranquilo es más efectivo." },
  { en: "Observe your thoughts without attachment.", es: "Observa tus pensamientos sin apego." },
  { en: "Patience brings a sense of ease.", es: "La paciencia aporta una sensación de facilidad." },
  { en: "Focus on what truly matters.", es: "Enfócate en lo que realmente importa." },
  { en: "Awareness brings light to shadows.", es: "La conciencia trae luz a las sombras." },
  { en: "Your path is guided by your heart.", es: "Tu camino es guiado por tu corazón." },
  { en: "Gentle attention reveals the path.", es: "La atención gentil revela el camino." },
  { en: "Stability grows from inner quiet.", es: "La estabilidad surge de la quietud interior." },
  { en: "Focus brings energy to your dreams.", es: "El enfoque aporta energía a tus sueños." },
  { en: "Observe the magic in the mundane.", es: "Observa la magia en lo mundano." },
  { en: "Patience is the bridge to clarity.", es: "La paciencia es el puente hacia la claridad." },

{ en: "Trust the flow of your own progress.", es: "Confía en el flujo de tu propio progreso." },
  { en: "Steady focus reveals hidden paths.", es: "El enfoque constante revela caminos ocultos." },
  { en: "Small adjustments lead to big changes.", es: "Pequeños ajustes llevan a grandes cambios." },
  { en: "Calmness allows clarity to surface.", es: "La calma permite que la claridad emerja." },
  { en: "Observe the rhythm of your day.", es: "Observa el ritmo de tu día." },
  { en: "Patience strengthens your resolve.", es: "La paciencia fortalece tu determinación." },
  { en: "Focus on the beauty of the process.", es: "Enfócate en la belleza del proceso." },
  { en: "Awareness brings a sense of freedom.", es: "La conciencia aporta una sensación de libertad." },
  { en: "Your energy is aligned with focus.", es: "Tu energía está alineada con el enfoque." },
  { en: "Gentle persistence leads to success.", es: "La persistencia gentil lleva al éxito." },
  { en: "Stability is a reflection of focus.", es: "La estabilidad es un reflejo del enfoque." },
  { en: "Observe the world with a calm mind.", es: "Observa el mundo con una mente tranquila." },
  { en: "Patience is the key to deep insight.", es: "La paciencia es la clave para una visión profunda." },
  { en: "Every moment is an opportunity to focus.", es: "Cada momento es una oportunidad para enfocarse." },
  { en: "Gentle awareness dissolves tension.", es: "La conciencia gentil disuelve la tensión." },
  { en: "Awareness keeps you in the flow.", es: "La conciencia te mantiene en el flujo." },
  { en: "Trust the timing of your life.", es: "Confía en los tiempos de tu vida." },
  { en: "Steady focus builds a clear path.", es: "El enfoque constante construye un camino claro." },
  { en: "Small refinements lead to growth.", es: "Pequeños refinamientos llevan al crecimiento." },
  { en: "Calm effort brings lasting peace.", es: "El esfuerzo tranquilo trae una paz duradera." },
  { en: "Observe the subtle dance of energy.", es: "Observa la danza sutil de la energía." },
  { en: "Patience allows the truth to emerge.", es: "La paciencia permite que la verdad emerja." },
  { en: "Focus brings clarity to your intent.", es: "El enfoque aporta claridad a tu intención." },
  { en: "Every step is a part of your journey.", es: "Cada paso es una parte de tu viaje." },
  { en: "Gentle focus leads to deep peace.", es: "El enfoque gentil lleva a una paz profunda." },
  { en: "Awareness is the mirror of the soul.", es: "La conciencia es el espejo del alma." },
  { en: "Your energy responds to quiet focus.", es: "Tu energía responde al enfoque silencioso." },
  { en: "Steady steps build a strong foundation.", es: "Los pasos constantes construyen una base sólida." },
  { en: "Small choices lead to great results.", es: "Pequeñas elecciones llevan a grandes resultados." },
  { en: "Calmness is the foundation of wisdom.", es: "La calma es la base de la sabiduría." },
  { en: "Observe without the need for control.", es: "Observa sin la necesidad de control." },
  { en: "Patience brings a deep sense of trust.", es: "La paciencia aporta un profundo sentido de confianza." },
  { en: "Focus on the light within you.", es: "Enfócate en la luz dentro de ti." },
  { en: "Awareness simplifies your path.", es: "La conciencia simplifica tu camino." },
  { en: "Your rhythm is perfectly timed.", es: "Tu ritmo está perfectamente sincronizado." },
  { en: "Gentle focus dissolves all worry.", es: "El enfoque gentil disuelve toda preocupación." },
  { en: "Stability grows with quiet attention.", es: "La estabilidad crece con la atención silenciosa." },
  { en: "Focus brings harmony to your life.", es: "El enfoque trae armonía a tu vida." },
  { en: "Observe the beauty in every breath.", es: "Observa la belleza en cada respiro." },
  { en: "Patience is the secret to flow.", es: "La paciencia es el secreto del flujo." },
  { en: "Every moment is a gift of awareness.", es: "Cada momento es un regalo de conciencia." },
  { en: "Gentle persistence creates momentum.", es: "La persistencia gentil genera impulso." },
  { en: "Awareness is the key to clarity.", es: "La conciencia es la clave de la claridad." },
  { en: "Trust the wisdom of your journey.", es: "Confía en la sabiduría de tu viaje." },
  { en: "Steady focus builds your reality.", es: "El enfoque constante construye tu realidad." },
  { en: "Small steps lead to big horizons.", es: "Pequeños pasos llevan a grandes horizontes." },
  { en: "Calm effort leads to true power.", es: "El esfuerzo tranquilo lleva al verdadero poder." },
  { en: "Observe the flow of life with ease.", es: "Observa el flujo de la vida con facilidad." },
  { en: "Patience is a form of quiet love.", es: "La paciencia es una forma de amor silencioso." },
  { en: "Focus on what brings you peace.", es: "Enfócate en lo que te trae paz." },
  { en: "Awareness brings understanding to all.", es: "La conciencia aporta entendimiento a todo." },
  { en: "Your path is unfolding perfectly.", es: "Tu camino se está desarrollando perfectamente." },
  { en: "Gentle attention clears the mind.", es: "La atención gentil despeja la mente." },
  { en: "Stability is found in the present.", es: "La estabilidad se encuentra en el presente." },
  { en: "Focus brings clarity to your world.", es: "El enfoque aporta claridad a tu mundo." },
  { en: "Observe the subtle magic of now.", es: "Observa la magia sutil del ahora." },
  { en: "Patience allows your light to shine.", es: "La paciencia permite que tu luz brille." },
  { en: "Every breath is a step toward peace.", es: "Cada respiro es un paso hacia la paz." },
  { en: "Gentle focus aligns your heart.", es: "El enfoque gentil alinea tu corazón." },
  { en: "Awareness is the bridge to growth.", es: "La conciencia es el puente hacia el crecimiento." },
  { en: "Trust your path as it unfolds.", es: "Confía en tu camino mientras se desarrolla." },
  { en: "Steady focus builds lasting change.", es: "El enfoque constante construye un cambio duradero." },
  { en: "Small refinements lead to wisdom.", es: "Pequeños refinamientos llevan a la sabiduría." },
  { en: "Calmness is the essence of strength.", es: "La calma es la esencia de la fuerza." },
  { en: "Observe with a quiet heart.", es: "Observa con un corazón tranquilo." },
  { en: "Patience is the seed of clarity.", es: "La paciencia es la semilla de la claridad." },
  { en: "Focus on the grace of the moment.", es: "Enfócate en la gracia del momento." },
  { en: "Awareness brings a sense of peace.", es: "La conciencia aporta una sensación de paz." },
  { en: "Your energy is focused and clear.", es: "Tu energía está enfocada y clara." },
  { en: "Gentle persistence yields success.", es: "La persistencia gentil da éxito." },
  { en: "Stability grows through attention.", es: "La estabilidad crece a través de la atención." },
  { en: "Observe the flow with confidence.", es: "Observa el flujo con confianza." },
  { en: "Patience allows for deep understanding.", es: "La paciencia permite un entendimiento profundo." },
  { en: "Every moment is a chance to align.", es: "Cada momento es una oportunidad para alinearse." },
  { en: "Gentle focus dissolves obstacles.", es: "El enfoque gentil disuelve los obstáculos." },
  { en: "Awareness keeps you in balance.", es: "La conciencia te mantiene en equilibrio." },
  { en: "Trust the rhythm of your heart.", es: "Confía en el ritmo de tu corazón." },
  { en: "Steady focus build a clear intent.", es: "El enfoque constante construye una intención clara." },
  { en: "Small choices guide your destiny.", es: "Pequeñas elecciones guían tu destino." },
  { en: "Calmness allows for true insight.", es: "La calma permite una visión verdadera." },
  { en: "Observe the world with kindness.", es: "Observa el mundo con amabilidad." },
  { en: "Patience is a quiet devotion.", es: "La paciencia es una devoción silenciosa." },
  { en: "Focus on the light of today.", es: "Enfócate en la luz de hoy." },
  { en: "Awareness brings ease to your life.", es: "La conciencia aporta facilidad a tu vida." },
  { en: "Your path is guided by grace.", es: "Tu camino es guiado por la gracia." },
  { en: "Gentle attention reveals the truth.", es: "La atención gentil revela la verdad." },
  { en: "Stability is found in quietness.", es: "La estabilidad se encuentra en la quietud." },
  { en: "Focus brings energy to your path.", es: "El enfoque aporta energía a tu camino." },
  { en: "Observe the magic in the flow.", es: "Observa la magia en el flujo." },
  { en: "Patience is the key to clarity.", es: "La paciencia es la clave de la claridad." },
  { en: "Every breath is a moment of peace.", es: "Cada respiro es un momento de paz." },
  { en: "Gentle focus aligns your purpose.", es: "El enfoque gentil alinea tu propósito." },
  { en: "Awareness is the light of wisdom.", es: "La conciencia es la luz de la sabiduría." },
  { en: "Trust your journey with ease.", es: "Confía en tu viaje con facilidad." },
  { en: "Steady focus reveals your strength.", es: "El enfoque constante revela tu fuerza." },
  { en: "Small steps build a great life.", es: "Pequeños pasos construyen una gran vida." },
  { en: "Calm effort is your best guide.", es: "El esfuerzo tranquilo es tu mejor guía." },
  { en: "Observe your world with love.", es: "Observa tu mundo con amor." },
  { en: "Patience brings a sense of flow.", es: "La paciencia aporta una sensación de flujo." },
  { en: "Focus on the peace within.", es: "Enfócate en la paz interior." },

{ en: "Trust your inner light today.", es: "Confía en tu luz interior hoy." },
  { en: "Steady focus reveals your path.", es: "El enfoque constante revela tu camino." },
  { en: "Small steps create lasting change.", es: "Pequeños pasos crean un cambio duradero." },
  { en: "Calmness brings clarity to life.", es: "La calma aporta claridad a la vida." },
  { en: "Observe the flow with an open mind.", es: "Observa el flujo con una mente abierta." },
  { en: "Patience is a form of quiet wisdom.", es: "La paciencia es una forma de sabiduría silenciosa." },
  { en: "Focus on what brings you joy.", es: "Enfócate en lo que te trae alegría." },
  { en: "Awareness brings understanding to now.", es: "La conciencia aporta entendimiento al ahora." },
  { en: "Your energy is focused and steady.", es: "Tu energía está enfocada y constante." },
  { en: "Gentle persistence leads to peace.", es: "La persistencia gentil lleva a la paz." },
  { en: "Stability grows through mindful focus.", es: "La estabilidad crece a través del enfoque consciente." },
  { en: "Observe the subtle dance of life.", es: "Observa la danza sutil de la vida." },
  { en: "Patience allows for true growth.", es: "La paciencia permite el verdadero crecimiento." },
  { en: "Every moment is a gift of focus.", es: "Cada momento es un regalo de enfoque." },
  { en: "Gentle awareness brings deep peace.", es: "La conciencia gentil trae una paz profunda." },
  { en: "Awareness keeps you centered and clear.", es: "La conciencia te mantiene centrado y claro." },
  { en: "Trust the timing of your progress.", es: "Confía en los tiempos de tu progreso." },
  { en: "Steady focus builds your future.", es: "El enfoque constante construye tu futuro." },
  { en: "Small refinements lead to success.", es: "Pequeños refinamientos llevan al éxito." },
  { en: "Calm effort yields beautiful results.", es: "El esfuerzo tranquilo da resultados hermosos." },
  { en: "Observe the world with steady eyes.", es: "Observa el mundo con ojos constantes." },
  { en: "Patience reveals the beauty within.", es: "La paciencia revela la belleza interior." },
  { en: "Focus brings clarity to every step.", es: "El enfoque aporta claridad a cada paso." },
  { en: "Every breath is a part of the whole.", es: "Cada respiro es una parte del todo." },
  { en: "Gentle focus leads to inner harmony.", es: "El enfoque gentil lleva a la armonía interior." },
  { en: "Awareness is the mirror of truth.", es: "La conciencia es el espejo de la verdad." },
  { en: "Your energy responds to gentle focus.", es: "Tu energía responde al enfoque gentil." },
  { en: "Steady steps build a firm path.", es: "Los pasos constantes construyen un camino firme." },
  { en: "Small choices lead to big results.", es: "Pequeñas elecciones llevan a grandes resultados." },
  { en: "Calmness is the foundation of peace.", es: "La calma es la base de la paz." },
  { en: "Observe without the need for judgment.", es: "Observa sin la necesidad de juzgar." },
  { en: "Patience brings a sense of deep trust.", es: "La paciencia aporta un sentido de confianza profunda." },
  { en: "Focus on the grace in every moment.", es: "Enfócate en la gracia en cada momento." },
  { en: "Awareness simplifies your journey.", es: "La conciencia simplifica tu viaje." },
  { en: "Your rhythm is steady and clear.", es: "Tu ritmo es constante y claro." },
  { en: "Gentle focus dissolves all resistance.", es: "El enfoque gentil disuelve toda resistencia." },
  { en: "Stability grows with quiet focus.", es: "La estabilidad crece con el enfoque silencioso." },
  { en: "Focus brings harmony to the present.", es: "El enfoque trae armonía al presente." },
  { en: "Observe the beauty in every breath.", es: "Observa la belleza en cada respiro." },
  { en: "Patience is the secret to true flow.", es: "La paciencia es el secreto del verdadero flujo." },
  { en: "Every moment is a chance for awareness.", es: "Cada momento es una oportunidad para la conciencia." },
  { en: "Gentle persistence creates new paths.", es: "La persistencia gentil crea nuevos caminos." },
  { en: "Awareness is the key to inner peace.", es: "La conciencia es la clave de la paz interior." },
  { en: "Trust the wisdom of the process.", es: "Confía en la sabiduría del proceso." },
  { en: "Steady focus builds your inner world.", es: "El enfoque constante construye tu mundo interior." },
  { en: "Small steps lead to great heights.", es: "Pequeños pasos llevan a grandes alturas." },
  { en: "Calm effort leads to true wisdom.", es: "El esfuerzo tranquilo lleva a la verdadera sabiduría." },
  { en: "Observe the flow of life with joy.", es: "Observa el flujo de la vida con alegría." },
  { en: "Patience is a form of inner strength.", es: "La paciencia es una forma de fuerza interior." },
  { en: "Focus on what brings you clarity.", es: "Enfócate en lo que te trae claridad." },
  { en: "Awareness brings light to all you do.", es: "La conciencia trae luz a todo lo que haces." },
  { en: "Your path is unfolding with grace.", es: "Tu camino se está desarrollando con gracia." },
  { en: "Gentle attention reveals your power.", es: "La atención gentil revela tu poder." },
  { en: "Stability is found in the now.", es: "La estabilidad se encuentra en el ahora." },
  { en: "Focus brings energy to your intent.", es: "El enfoque aporta energía a tu intención." },
  { en: "Observe the subtle magic of life.", es: "Observa la magia sutil de la vida." },
  { en: "Patience allows your wisdom to grow.", es: "La paciencia permite que tu sabiduría crezca." },
  { en: "Every breath is a step toward focus.", es: "Cada respiro es un paso hacia el enfoque." },
  { en: "Gentle focus aligns your inner self.", es: "El enfoque gentil alinea tu ser interior." },
  { en: "Awareness is the light on your journey.", es: "La conciencia es la luz en tu viaje." },
  { en: "Trust the path as it opens before you.", es: "Confía en el camino mientras se abre ante ti." },
  { en: "Steady focus builds a clear vision.", es: "El enfoque constante construye una visión clara." },
  { en: "Small refinements lead to deep insight.", es: "Pequeños refinamientos llevan a una visión profunda." },
  { en: "Calmness is the essence of balance.", es: "La calma es la esencia del equilibrio." },
  { en: "Observe with a quiet and open heart.", es: "Observa con un corazón tranquilo y abierto." },
  { en: "Patience is the seed of true clarity.", es: "La paciencia es la semilla de la verdadera claridad." },
  { en: "Focus on the grace of the present.", es: "Enfócate en la gracia del presente." },
  { en: "Awareness brings peace to your actions.", es: "La conciencia aporta paz a tus acciones." },
  { en: "Your energy is aligned with your intent.", es: "Tu energía está alineada con tu intención." },
  { en: "Gentle persistence leads to fulfillment.", es: "La persistencia gentil lleva a la plenitud." },
  { en: "Stability grows through gentle attention.", es: "La estabilidad crece a través de la atención gentil." },
  { en: "Observe the flow with inner calm.", es: "Observa el flujo con calma interior." },
  { en: "Patience allows for natural clarity.", es: "La paciencia permite la claridad natural." },
  { en: "Every moment is a chance to be present.", es: "Cada momento es una oportunidad para estar presente." },
  { en: "Gentle focus dissolves all obstacles.", es: "El enfoque gentil disuelve todos los obstáculos." },
  { en: "Awareness keeps you in perfect balance.", es: "La conciencia te mantiene en perfecto equilibrio." },
  { en: "Trust the rhythm of your inner voice.", es: "Confía en el ritmo de tu voz interior." },
  { en: "Steady focus builds a clear purpose.", es: "El enfoque constante construye un propósito claro." },
  { en: "Small choices lead to great wisdom.", es: "Pequeñas elecciones llevan a una gran sabiduría." },
  { en: "Calmness allows for deep insight.", es: "La calma permite una visión profunda." },
  { en: "Observe the world with a gentle heart.", es: "Observa el mundo con un corazón gentil." },
  { en: "Patience is a form of deep devotion.", es: "La paciencia es una forma de devoción profunda." },
  { en: "Focus on the light of the present.", es: "Enfócate en la luz del presente." },
  { en: "Awareness brings ease to your day.", es: "La conciencia aporta facilidad a tu día." },
  { en: "Your path is guided by inner truth.", es: "Tu camino es guiado por la verdad interior." },
  { en: "Gentle attention reveals the way.", es: "La atención gentil revela el camino." },
  { en: "Stability is found in the quiet moments.", es: "La estabilidad se encuentra en los momentos de quietud." },
  { en: "Focus brings energy to your life path.", es: "El enfoque aporta energía al camino de tu vida." },
  { en: "Observe the beauty in the flow.", es: "Observa la belleza en el flujo." },
  { en: "Patience is the key to deep clarity.", es: "La paciencia es la clave para una claridad profunda." },
  { en: "Every breath is a gift of peace.", es: "Cada respiro es un regalo de paz." },
  { en: "Gentle focus aligns your spirit.", es: "El enfoque gentil alinea tu espíritu." },
  { en: "Awareness is the light of understanding.", es: "La conciencia es la luz del entendimiento." },
  { en: "Trust your journey with inner peace.", es: "Confía en tu viaje con paz interior." },
  { en: "Steady focus builds your strength.", es: "El enfoque constante construye tu fuerza." },
  { en: "Small steps build a great vision.", es: "Pequeños pasos construyen una gran visión." },
  { en: "Calm effort is your quiet guide.", es: "El esfuerzo tranquilo es tu guía silenciosa." },
  { en: "Observe your world with compassion.", es: "Observa tu mundo con compasión." },
  { en: "Patience brings a sense of deep flow.", es: "La paciencia aporta una sensación de flujo profundo." },
  { en: "Focus on the peace that is within.", es: "Enfócate en la paz que está en el interior." },

{ en: "Trust the wisdom of your quiet mind.", es: "Confía en la sabiduría de tu mente tranquila." },
  { en: "Steady focus reveals your inner strength.", es: "El enfoque constante revela tu fuerza interior." },
  { en: "Small steps build a beautiful life.", es: "Pequeños pasos construyen una vida hermosa." },
  { en: "Calm effort is your most reliable guide.", es: "El esfuerzo tranquilo es tu guía más confiable." },
  { en: "Observe your journey with an open heart.", es: "Observa tu viaje con un corazón abierto." },
  { en: "Patience brings a sense of natural flow.", es: "La paciencia aporta una sensación de flujo natural." },
  { en: "Focus on the peace that lives within.", es: "Enfócate en la paz que vive en tu interior." },
  { en: "Awareness brings light to your daily path.", es: "La conciencia trae luz a tu camino diario." },
  { en: "Your energy is aligned and clear today.", es: "Tu energía está alineada y clara hoy." },
  { en: "Gentle persistence leads to deep fulfillment.", es: "La persistencia gentil lleva a una plenitud profunda." },
  { en: "Stability grows from mindful attention.", es: "La estabilidad surge de la atención consciente." },
  { en: "Observe the subtle beauty of existence.", es: "Observa la belleza sutil de la existencia." },
  { en: "Patience allows your potential to mature.", es: "La paciencia permite que tu potencial madure." },
  { en: "Every moment is a chance to stay focused.", es: "Cada momento es una oportunidad para mantener el enfoque." },
  { en: "Gentle awareness dissolves all tension.", es: "La conciencia gentil disuelve toda tensión." },
  { en: "Awareness keeps you in perfect rhythm.", es: "La conciencia te mantiene en un ritmo perfecto." },
  { en: "Trust the timing of your own unfolding.", es: "Confía en los tiempos de tu propio desarrollo." },
  { en: "Steady focus builds a bright future.", es: "El enfoque constante construye un futuro brillante." },
  { en: "Small refinements lead to great growth.", es: "Pequeños refinamientos llevan a un gran crecimiento." },
  { en: "Calm effort brings lasting results.", es: "El esfuerzo tranquilo trae resultados duraderos." },
  { en: "Observe the dance of life with ease.", es: "Observa la danza de la vida con facilidad." },
  { en: "Patience reveals the truth of the heart.", es: "La paciencia revela la verdad del corazón." },
  { en: "Focus brings clarity to your vision.", es: "El enfoque aporta claridad a tu visión." },
  { en: "Every breath is a sacred part of now.", es: "Cada respiro es una parte sagrada del ahora." },
  { en: "Gentle focus leads to inner quiet.", es: "El enfoque gentil lleva a la quietud interior." },
  { en: "Awareness is the mirror of your essence.", es: "La conciencia es el espejo de tu esencia." },
  { en: "Your energy responds to patient focus.", es: "Tu energía responde al enfoque paciente." },
  { en: "Steady steps build a solid foundation.", es: "Los pasos constantes construyen una base sólida." },
  { en: "Small choices lead to meaningful results.", es: "Pequeñas elecciones llevan a resultados significativos." },
  { en: "Calmness is the source of true peace.", es: "La calma es la fuente de la verdadera paz." },
  { en: "Observe without the need to evaluate.", es: "Observa sin la necesidad de evaluar." },
  { en: "Patience brings a deep sense of calm.", es: "La paciencia aporta una profunda sensación de calma." },
  { en: "Focus on the grace within the moment.", es: "Enfócate en la gracia dentro del momento." },
  { en: "Awareness simplifies the way forward.", es: "La conciencia simplifica el camino a seguir." },
  { en: "Your rhythm is steady and purposeful.", es: "Tu ritmo es constante y con propósito." },
  { en: "Gentle focus dissolves inner resistance.", es: "El enfoque gentil disuelve la resistencia interior." },
  { en: "Stability grows with steady attention.", es: "La estabilidad crece con la atención constante." },
  { en: "Focus brings harmony to your world.", es: "El enfoque trae armonía a tu mundo." },
  { en: "Observe the miracle in every breath.", es: "Observa el milagro en cada respiro." },
  { en: "Patience is the secret to lasting flow.", es: "La paciencia es el secreto del flujo duradero." },
  { en: "Every moment is a gift of presence.", es: "Cada momento es un regalo de presencia." },
  { en: "Gentle persistence builds momentum.", es: "La persistencia gentil genera impulso." },
  { en: "Awareness is the light of your soul.", es: "La conciencia es la luz de tu alma." },
  { en: "Trust the wisdom of your path.", es: "Confía en la sabiduría de tu camino." },
  { en: "Steady focus shapes your destiny.", es: "El enfoque constante moldea tu destino." },
  { en: "Small steps lead to vast horizons.", es: "Pequeños pasos llevan a horizontes vastos." },
  { en: "Calm effort leads to deep wisdom.", es: "El esfuerzo tranquilo lleva a una profunda sabiduría." },
  { en: "Observe life with a peaceful heart.", es: "Observa la vida con un corazón pacífico." },
  { en: "Patience is a form of inner light.", es: "La paciencia es una forma de luz interior." },
  { en: "Focus on what brings you clarity.", es: "Enfócate en lo que te trae claridad." },
  { en: "Awareness brings light to your soul.", es: "La conciencia trae luz a tu alma." },
  { en: "Your path is guided by gentle grace.", es: "Tu camino es guiado por una gracia gentil." },
  { en: "Gentle attention reveals your truth.", es: "La atención gentil revela tu verdad." },
  { en: "Stability is found in this moment.", es: "La estabilidad se encuentra en este momento." },
  { en: "Focus brings energy to your path.", es: "El enfoque aporta energía a tu camino." },
  { en: "Observe the subtle magic around you.", es: "Observa la magia sutil a tu alrededor." },
  { en: "Patience allows your wisdom to shine.", es: "La paciencia permite que tu sabiduría brille." },
  { en: "Every breath is a step to alignment.", es: "Cada respiro es un paso hacia la alineación." },
  { en: "Gentle focus aligns your inner world.", es: "El enfoque gentil alinea tu mundo interior." },
  { en: "Awareness is the key to your journey.", es: "La conciencia es la clave de tu viaje." },
  { en: "Trust the path as it opens today.", es: "Confía en el camino mientras se abre hoy." },
  { en: "Steady focus builds a clear purpose.", es: "El enfoque constante construye un propósito claro." },
  { en: "Small refinements lead to clarity.", es: "Pequeños refinamientos llevan a la claridad." },
  { en: "Calmness is the essence of wisdom.", es: "La calma es la esencia de la sabiduría." },
  { en: "Observe with a quiet and open mind.", es: "Observa con una mente tranquila y abierta." },
  { en: "Patience is the seed of deep peace.", es: "La paciencia es la semilla de una paz profunda." },
  { en: "Focus on the grace of being here.", es: "Enfócate en la gracia de estar aquí." },
  { en: "Awareness brings peace to your mind.", es: "La conciencia trae paz a tu mente." },
  { en: "Your energy is aligned with focus.", es: "Tu energía está alineada con el enfoque." },
  { en: "Gentle persistence leads to fulfillment.", es: "La persistencia gentil lleva a la plenitud." },
  { en: "Stability grows from quiet attention.", es: "La estabilidad surge de la atención silenciosa." },
  { en: "Observe the flow with confidence.", es: "Observa el flujo con confianza." },
  { en: "Patience allows for true insight.", es: "La paciencia permite una visión verdadera." },
  { en: "Every moment is a chance to align.", es: "Cada momento es una oportunidad para alinearse." },
  { en: "Gentle focus dissolves obstacles.", es: "El enfoque gentil disuelve los obstáculos." },
  { en: "Awareness keeps you in balance.", es: "La conciencia te mantiene en equilibrio." },
  { en: "Trust the rhythm of your heart.", es: "Confía en el ritmo de tu corazón." },
  { en: "Steady focus builds clear intent.", es: "El enfoque constante construye una intención clara." },
  { en: "Small choices guide your direction.", es: "Pequeñas elecciones guían tu dirección." },
  { en: "Calmness allows for wisdom to emerge.", es: "La calma permite que la sabiduría emerja." },
  { en: "Observe the world with kindness.", es: "Observa el mundo con amabilidad." },
  { en: "Patience is a quiet devotion.", es: "La paciencia es una devoción silenciosa." },
  { en: "Focus on the light of today.", es: "Enfócate en la luz de hoy." },
  { en: "Awareness brings ease to your life.", es: "La conciencia aporta facilidad a tu vida." },
  { en: "Your path is guided by grace.", es: "Tu camino es guiado por la gracia." },
  { en: "Gentle attention reveals the truth.", es: "La atención gentil revela la verdad." },
  { en: "Stability is found in quietness.", es: "La estabilidad se encuentra en la quietud." },
  { en: "Focus brings energy to your journey.", es: "El enfoque aporta energía a tu viaje." },
  { en: "Observe the magic in the flow.", es: "Observa la magia en el flujo." },
  { en: "Patience is the key to clarity.", es: "La paciencia es la clave de la claridad." },
  { en: "Every breath is a moment of peace.", es: "Cada respiro es un momento de paz." },
  { en: "Gentle focus aligns your spirit.", es: "El enfoque gentil alinea tu espíritu." },
  { en: "Awareness is the light of wisdom.", es: "La conciencia es la luz de la sabiduría." },
  { en: "Trust your journey with ease.", es: "Confía en tu viaje con facilidad." },
  { en: "Steady focus reveals your strength.", es: "El enfoque constante revela tu fuerza." },
  { en: "Small steps build a great life.", es: "Pequeños pasos construyen una gran vida." },
  { en: "Calm effort is your best guide.", es: "El esfuerzo tranquilo es tu mejor guía." },
  { en: "Observe your world with love.", es: "Observa tu mundo con amor." },
  { en: "Patience brings a sense of flow.", es: "La paciencia aporta una sensación de flujo." },
  { en: "Focus on the peace within.", es: "Enfócate en la paz interior." }
];








